### PR TITLE
#-11 Button and Alert Component

### PR DESCRIPTION
**Pull request by Koushith**
## Description

- [x] Bootstrapped the Project.
- [x] Adds Alert component.
- [x] Adds Button component.

## TODO - 
- [ ] Docs site. -WIP

## Screenshot and Code Snippets

https://www.loom.com/share/c185ac2a860346ae9957eb9dab071949
image
image
image

## Platform tested

- [x] Web
- [x] Tablet
- [x] Mobile

### CODE REVIEW

**Review by sakshi006 — COMMENTED** [review]
Looks good to me.

**Review by sakshi006 — APPROVED** [review]

**Comment by TusharJade** [comment]
Looks good bro

**Comment by Koushith** [comment]
> Looks good bro

Thanks for the review

**Comment by Koushith** [comment]
> Looks good to me.

Thanks for the review.

**Pull request merged**
