### PR TITLE
P1 -Feature - List component

### PR DESCRIPTION
**Pull request by Koushith**
## Description

 - [x] Adds list component

## Screenshot and Code Snippets

https://www.loom.com/share/8bf16f222efe40bf9819fabf069b9150

### CODE REVIEW

**Review by kr-sarvesh — COMMENTED** [review]
loved your user interface

**Review by Balakumar3018 — APPROVED** [review]
Good to go.
Suggestion -  it would be better if you make same width for all iframes

**Comment by Koushith** [comment]
> loved your user interface

Thanks @kr-sarvesh

**Comment by Koushith** [comment]
> Good to go. Suggestion - it would be better if you make same width for all iframes

Thanks man. will fix that while polishing.

**Pull request merged**
